export const THEMES = [
  {
    name: "light",
    label: "Light",
    colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
  },
  {
    name: "dark",
    label: "Dark",
    colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"],
  },
  {
    name: "cupcake",
    label: "Cupcake",
    colors: ["#f5f5f4", "#65c3c8", "#ef9fbc", "#291334"],
  },
  {
    name: "forest",
    label: "Forest",
    colors: ["#1f1d1d", "#3ebc96", "#70c217", "#e2e8f0"],
  },
  {
    name: "bumblebee",
    label: "Bumblebee",
    colors: ["#ffffff", "#f8e36f", "#f0d50c", "#1c1917"],
  },
  {
    name: "emerald",
    label: "Emerald",
    colors: ["#ffffff", "#66cc8a", "#3b82f6", "#1e3a8a"],
  },
  {
    name: "corporate",
    label: "Corporate",
    colors: ["#ffffff", "#4b6bfb", "#7b92b2", "#1d232a"],
  },
  {
    name: "synthwave",
    label: "Synthwave",
    colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"],
  },
  {
    name: "retro",
    label: "Retro",
    colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"],
  },
  {
    name: "cyberpunk",
    label: "Cyberpunk",
    colors: ["#ffee00", "#ff7598", "#75d1f0", "#1a103d"],
  },
  {
    name: "valentine",
    label: "Valentine",
    colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"],
  },
  {
    name: "halloween",
    label: "Halloween",
    colors: ["#0d0d0d", "#ff7800", "#006400", "#ffffff"],
  },
  {
    name: "garden",
    label: "Garden",
    colors: ["#e9e7e7", "#ec4899", "#16a34a", "#374151"],
  },

  {
    name: "aqua",
    label: "Aqua",
    colors: ["#193549", "#4cd4e3", "#9059ff", "#f8d766"],
  },
  {
    name: "lofi",
    label: "Lofi",
    colors: ["#0f0f0f", "#1a1919", "#232323", "#2c2c2c"],
  },
  {
    name: "pastel",
    label: "Pastel",
    colors: ["#f7f3f5", "#d1c1d7", "#a1e3d8", "#4a98f1"],
  },
  {
    name: "fantasy",
    label: "Fantasy",
    colors: ["#ffe7d6", "#a21caf", "#3b82f6", "#f59e0b"],
  },
  {
    name: "wireframe",
    label: "Wireframe",
    colors: ["#e6e6e6", "#b3b3b3", "#b3b3b3", "#888888"],
  },
  {
    name: "black",
    label: "Black",
    colors: ["#000000", "#191919", "#313131", "#4a4a4a"],
  },
  {
    name: "luxury",
    label: "Luxury",
    colors: ["#171618", "#1e293b", "#94589c", "#d4a85a"],
  },
  {
    name: "dracula",
    label: "Dracula",
    colors: ["#282a36", "#ff79c6", "#bd93f9", "#f8f8f2"],
  },
  {
    name: "cmyk",
    label: "CMYK",
    colors: ["#f0f0f0", "#0891b2", "#ec4899", "#facc15"],
  },
  {
    name: "autumn",
    label: "Autumn",
    colors: ["#f2f2f2", "#8c1f11", "#f28c18", "#6f4930"],
  },
  {
    name: "business",
    label: "Business",
    colors: ["#f5f5f5", "#1e40af", "#3b82f6", "#f97316"],
  },
  {
    name: "acid",
    label: "Acid",
    colors: ["#110e0e", "#ff00f2", "#ff7a00", "#99ff01"],
  },
  {
    name: "lemonade",
    label: "Lemonade",
    colors: ["#ffffff", "#67e8f9", "#f5d742", "#2c3333"],
  },
  {
    name: "night",
    label: "Night",
    colors: ["#0f172a", "#38bdf8", "#818cf8", "#e2e8f0"],
  },
  {
    name: "coffee",
    label: "Coffee",
    colors: ["#20161f", "#dd9866", "#497174", "#eeeeee"],
  },
  {
    name: "winter",
    label: "Winter",
    colors: ["#ffffff", "#0284c7", "#d946ef", "#0f172a"],
  },
  {
    name: "dim",
    label: "Dim",
    colors: ["#1c1c27", "#10b981", "#ff5a5f", "#0f172a"],
  },
  {
    name: "nord",
    label: "Nord",
    colors: ["#eceff4", "#5e81ac", "#81a1c1", "#3b4252"],
  },
  {
    name: "sunset",
    label: "Sunset",
    colors: ["#1e293b", "#f5734c", "#ec4899", "#ffffff"],
  },
];

export const ALL_LANGUAGES = [
  "Akan", "Amharic", "Arabic", "Assamese", "Awadhi", "Azerbaijani", "Balochi", "Belarusian", "Bengali", "Bhojpuri", 
  "Burmese", "Chewa", "Chittagonian", "Czech", "Deccan", "Dhundhari", "Dutch", "English", "French", "Fula", 
  "German", "Greek", "Gujarati", "Haitian Creole", "Haryanvi", "Hiligaynon", "Hindi", "Hmong", "Hungarian", "Igbo", 
  "Ilokano", "Indonesian", "Italian", "Japanese", "Javanese", "Kannada", "Kazakh", "Khmer", "Kinyarwanda", "Kirundi", 
  "Konkani", "Korean", "Kurdish", "Lao", "Magahi", "Maithili", "Malagasy", "Malayalam", "Mandarin", "Marathi", "Marwari", "Min Nan", "Mossi", 
  "Nepali", "Odia", "Oromo", "Pashto", "Polish", "Portuguese", "Quechua", "Romanian", "Russian", "Serbo-Croatian", 
  "Shona", "Sindhi", "Sinhalese", "Somali", "Spanish", "Swahili", "Swedish", "Sylheti", "Tagalog", "Tamil", 
  "Telugu", "Thai", "Tibetan", "Turkmen", "Turkish", "Ukrainian", "Urdu", "Uyghur", "Uzbek", "Vietnamese", 
  "Xhosa", "Yi", "Yoruba", "Zhuang", "Zulu"
];

export const ALL_COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
  "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
  "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the",
  "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland",
  "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
  "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq",
  "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North",
  "Korea, South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
  "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands",
  "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique",
  "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia",
  "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
  "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa",
  "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
  "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland",
  "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
  "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
  "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

export const LANGUAGE_TO_FLAG = {
  English: "gb",
  Spanish: "es",
  Mandarin: "cn",
  Hindi: "in",
  French: "fr",
  Arabic: "sa",
  Bengali: "bd",
  Portuguese: "pt",
  Russian: "ru",
  Urdu: "pk",
  Indonesian: "id",
  German: "de",
  Japanese: "jp",
  Swahili: "ke",
  Marathi: "in",
  Telugu: "in",
  Turkish: "tr",
  Korean: "kr",
  Tamil: "in",
  Vietnamese: "vn",
  Italian: "it",
  Javanese: "id",
  Thai: "th",
  Gujarati: "in",
  Polish: "pl",
  Pashto: "af",
  Kannada: "in",
  Malayalam: "in",
  Odia: "in",
  Burmese: "mm",
  Ukrainian: "ua",
  Bhojpuri: "in",
  Tagalog: "ph",
  Yoruba: "ng",
  Maithili: "in",
  Uzbek: "uz",
  Sindhi: "pk",
  Amharic: "et",
  Fula: "sn",
  Romanian: "ro",
  Oromo: "et",
  Igbo: "ng",
  Azerbaijani: "az",
  Awadhi: "in",
  Dutch: "nl",
  Kurdish: "iq",
  "Serbo-Croatian": "hr", 
  Malagasy: "mg",
  Nepali: "np",
  Sinhalese: "lk",
  Chittagonian: "bd",
  Khmer: "kh",
  Assamese: "in",
  Madurese: "id",
  Somali: "so",
  Marwari: "in",
  Magahi: "in",
  Haryanvi: "in",
  Greek: "gr",
  Chewa: "mw",
  Deccan: "in",
  Akan: "gh",
  Kazakh: "kz",
  Sylheti: "bd",
  Zulu: "za",
  Czech: "cz",
  Kinyarwanda: "rw",
  Dhundhari: "in",
  "haitian creole": "ht",
  "min nan": "cn", 
  Ilokano: "ph",
  Quechua: "pe",
  Kirundi: "bi",
  Swedish: "se",
  Hmong: "la", 
  Shona: "zw",
  Uyghur: "cn",
  Hiligaynon: "ph",
  Mossi: "bf",
  Xhosa: "za",
  Belarusian: "by",
  Balochi: "pk",
  Konkani: "in",
  Hungarian: "hu",
  Turkmen: "tm",
  Zhuang: "cn",
  Yi: "cn",
  Lao: "la",
  Tibetan: "cn",
};
export const INTERESTS_LIST = [
    // Công nghệ & Học tập
    "Coding", "Web Dev", "AI & ML", "Design", "Reading", "History", "Science", "Psychology", "Languages",
    
    // Giải trí & Nghệ thuật
    "Gaming", "Anime", "Manga", "Movies", "K-Pop", "Music", "Guitar", "Piano", "Singing", "Drawing", "Photography",
    
    // Thể thao & Sức khỏe
    "Football", "Basketball", "Badminton", "Yoga", "Gym", "Running", "Cycling", "Meditation",
    
    // Đời sống & Du lịch
    "Travel", "Camping", "Cooking", "Baking", "Coffee", "Foodie", "Gardening", "DIY", "Fashion", "Pets"
];